/**
 * MCP initialize instructions — returned to AI agents on connect.
 * Emphasizes common mistakes that cause third-party auth failures (e.g. Searchengine).
 */
export const MCP_SERVER_INSTRUCTIONS = `
# CNothing AuthAI KV — Agent Instructions

CNothing stores third-party credentials (API keys, tokens) so AI agents can orchestrate flows without seeing plaintext secrets. Agents MUST forward opaque envelopes only; trusted backends hold private keys and build envelopes.

## Three public keys — never mix them up

| Key | Source | Use when |
| --- | --- | --- |
| **CNothing AuthAI public key** | \`get_authai_public_key\` | Backend encrypts \`auth_envelope\`, \`data_envelope\`, \`query_envelope\` to CNothing; also give to third parties when they issue credentials encrypted **to CNothing** |
| **Client public key** | Generated by trusted backend | \`authai_register\`; backend decrypts \`challenge_for_client\`; \`recipient_public_key\` on \`kv_read\` **only** when the **client backend** (not a third-party service) consumes the secret |
| **Third-party service public key** | Published by the third party (e.g. Searchengine \`GET /v1/auth/public-key\`) | \`recipient_public_key\` on \`kv_read\` when the **third-party service** will decrypt and use the credential for auth |

## kv_read / kv_save rules

- \`kv_read\` **requires** \`recipient_public_key\`: results are encrypted to that key before the AI sees them.
- For ksp1-stored credentials, each item value in the decrypted result is a **new ksp1 envelope** re-encrypted to \`recipient_public_key\`.
- \`result_envelope_for_client\` is also encrypted to \`recipient_public_key\`. Only the holder of the matching private key can decrypt it.

## Common mistakes (cause third-party auth failures)

### 1. Wrong \`recipient_public_key\` on kv_read

**Wrong:** CNothing AuthAI public key or client public key when the consumer is a third-party service (e.g. Searchengine).

**Right:** Third-party service public key (for Searchengine: \`GET /v1/auth/public-key\` on the search-api host, field \`search_api_public_key.public_key_pem\`).

**Symptom at third party:** \`Failed to decrypt encrypted_key\` — RSA layer was encrypted for a different key.

### 2. Storing a reader-encrypted envelope without backend decrypt (Searchengine flow)

**Wrong:** Save \`authenticate_agent\` \`api_key_envelope\` (encrypted to **reader_public_key**) directly via \`kv_save\` as the stored value.

**Right:** Trusted backend decrypts with **reader private key**, then \`kv_save\` stores plaintext JSON \`{ api_key, client_uuid, ... }\` inside \`data_envelope\`, or a ksp1 envelope encrypted to **CNothing AuthAI** public key (standard third-party issue flow).

**Symptom at Searchengine after kv_read with correct recipient:** \`Failed to decrypt encrypted_key\` (nested reader envelope inside a search-api outer wrap).

### 3. Confusing protocol envelopes with credential envelopes

**Wrong:** Use \`get_authai_public_key\` output as \`recipient_public_key\` for reading credentials destined for Searchengine.

**Right:** AuthAI public key is for envelopes **to CNothing** only. Credential delivery **to Searchengine** uses Searchengine's public key.

### 4. Sending \`result_envelope_for_client\` to Searchengine as \`api_key_envelope\`

**Wrong:** Pass the entire \`kv_read\` \`result_envelope_for_client\` blob as Searchengine search \`api_key_envelope\`.

**Right:** Holder of recipient private key decrypts \`result_envelope_for_client\`, extracts the ksp1 envelope from \`items[<key>]\`, then passes **that inner ksp1 object** to Searchengine (or injects \`X-Search-API-Key-Envelope\`). Agent cannot extract \`items\` without backend decrypt.

**Symptom at Searchengine:** \`Decrypted envelope missing api_key\` (outer kv.read.result wrapper, not an api_key payload).

### 5. Agent tries to decrypt or re-encrypt

**Wrong:** Agent decrypts any envelope, or encrypts api_key with a public key without backend involvement.

**Right:** Agent forwards ciphertext; backend performs all decrypt/encrypt steps that require private keys or plaintext api_key.

## Searchengine integration checklist

1. CNothing: \`authai_register\` → backend decrypts challenge.
2. Searchengine MCP: \`authenticate_agent\` with \`reader_public_key\` → returns \`api_key_envelope\` (**reader-encrypted only**).
3. Backend: decrypt \`api_key_envelope\` with reader private key → \`kv_save\` plaintext credential (namespace e.g. \`searchengine\`).
4. For search with encrypted api_key:
   - Backend \`kv_read\` with \`recipient_public_key\` = Searchengine \`GET /v1/auth/public-key\`, decrypts \`result_envelope_for_client\`, injects inner ksp1 to search; **or**
   - **Recommended for autonomous agents:** each search call uses \`client_uuid\` + fresh \`auth_envelope\` (no api_key envelope).

Read \`/docs/mcp.md\` and \`/standards/registration-hub\` for full protocol details.
`.trim();
